/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'teams' : IDL.Vec(IDL.Text),
  'organizer' : IDL.Principal,
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'description' : IDL.Text,
  'winningTeam' : IDL.Opt(IDL.Text),
  'registeredParticipants' : IDL.Vec(IDL.Principal),
  'dateTime' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'organizer' : IDL.Null,
  'participant' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const Team = IDL.Record({
  'id' : IDL.Text,
  'eventId' : IDL.Text,
  'creator' : IDL.Principal,
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'inviteLink' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'checkIn' : IDL.Func([IDL.Text], [], []),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createTeam' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'declareWinner' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCheckedInParticipants' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
  'getEventRegistrations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getEventStatistics' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'teamCount' : IDL.Nat,
          'checkInCount' : IDL.Nat,
          'registrationCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getEventTeams' : IDL.Func([IDL.Text], [IDL.Vec(Team)], ['query']),
  'getMyEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getTeam' : IDL.Func([IDL.Text], [IDL.Opt(Team)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTeam' : IDL.Func([IDL.Text], [], []),
  'leaveTeam' : IDL.Func([IDL.Text], [], []),
  'registerForEvent' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unregisterFromEvent' : IDL.Func([IDL.Text], [], []),
  'updateEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'teams' : IDL.Vec(IDL.Text),
    'organizer' : IDL.Principal,
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'description' : IDL.Text,
    'winningTeam' : IDL.Opt(IDL.Text),
    'registeredParticipants' : IDL.Vec(IDL.Principal),
    'dateTime' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'organizer' : IDL.Null,
    'participant' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const Team = IDL.Record({
    'id' : IDL.Text,
    'eventId' : IDL.Text,
    'creator' : IDL.Principal,
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'inviteLink' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'checkIn' : IDL.Func([IDL.Text], [], []),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createTeam' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'declareWinner' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCheckedInParticipants' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getEvent' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
    'getEventRegistrations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getEventStatistics' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'teamCount' : IDL.Nat,
            'checkInCount' : IDL.Nat,
            'registrationCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getEventTeams' : IDL.Func([IDL.Text], [IDL.Vec(Team)], ['query']),
    'getMyEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getTeam' : IDL.Func([IDL.Text], [IDL.Opt(Team)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTeam' : IDL.Func([IDL.Text], [], []),
    'leaveTeam' : IDL.Func([IDL.Text], [], []),
    'registerForEvent' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unregisterFromEvent' : IDL.Func([IDL.Text], [], []),
    'updateEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };