/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Event {
  'id' : string,
  'teams' : Array<string>,
  'organizer' : Principal,
  'title' : string,
  'venue' : string,
  'description' : string,
  'winningTeam' : [] | [string],
  'registeredParticipants' : Array<Principal>,
  'dateTime' : string,
}
export interface Team {
  'id' : string,
  'eventId' : string,
  'creator' : Principal,
  'members' : Array<Principal>,
  'name' : string,
  'inviteLink' : string,
}
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'organizer' : null } |
  { 'participant' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'checkIn' : ActorMethod<[string], undefined>,
  'createEvent' : ActorMethod<[string, string, string, string], string>,
  'createTeam' : ActorMethod<[string, string], string>,
  'declareWinner' : ActorMethod<[string, string], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCheckedInParticipants' : ActorMethod<[string], Array<Principal>>,
  'getEvent' : ActorMethod<[string], [] | [Event]>,
  'getEventRegistrations' : ActorMethod<[string], Array<Principal>>,
  'getEventStatistics' : ActorMethod<
    [string],
    {
      'teamCount' : bigint,
      'checkInCount' : bigint,
      'registrationCount' : bigint,
    }
  >,
  'getEventTeams' : ActorMethod<[string], Array<Team>>,
  'getMyEvents' : ActorMethod<[], Array<Event>>,
  'getTeam' : ActorMethod<[string], [] | [Team]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinTeam' : ActorMethod<[string], undefined>,
  'leaveTeam' : ActorMethod<[string], undefined>,
  'registerForEvent' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unregisterFromEvent' : ActorMethod<[string], undefined>,
  'updateEvent' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];